name: Build project

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(git rev-parse --short HEAD)"
      - name: Update and install packages
        run: |
          apt-get -qq update
          ACCEPT_EULA=Y apt-get -y dist-upgrade
          apt-get -y install cmake libhidapi-dev lsb-release wget libminizip-dev libsdl2-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev pkg-config zlib1g-dev binutils-dev libspeexdsp-dev libsamplerate0-dev qt5-default build-essential nasm git zip libsdl2-net-dev libqt5websockets5-dev
      - name: Run build script
        run: |
          export M64P_AUTOUPDATE=0
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          bash ./build.sh
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: m64p-linux64-${{ steps.slug.outputs.sha7 }}.zip
          path: m64p-*.zip
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(git rev-parse --short HEAD)"
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libsamplerate
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_net
            mingw-w64-x86_64-jasper
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-python3-pip
            mingw-w64-x86_64-python3-pyopenssl
            mingw-w64-x86_64-pcre
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-md4c
            git
            zip
      - name: Run build script
        run: msys2 -c 'export M64P_AUTOUPDATE=0; ./build.sh'
        env:
          HOST_CPU: x86_64
          MSBUILD_PATH: "/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/"
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: m64p-win64-${{ steps.slug.outputs.sha7 }}.zip
          path: m64p-*.zip
